### PR TITLE
Enhancement / Add FakeBeer

### LINKED ISSUE #36: Add Fake Beer
Add a `FakeBeer` instance to `FakeContext`. Please ensure that new properties are added in alphabetical order and well documented.

Here are points of reference from the `Faker` library:

```kotlin
val beer = faker.beer()
beer.hop()
beer.malt()
beer.name()
beer.style()
beer.yeast()
```

If you want to work on this please leave a comment so you can be assigned to this issue. Feel free to ask questions or open a draft PR if you are unsure on implementation details.

### PR DESCRIPTION
**Pull request by mattkimmel**
Closes #36 

## Description
Creates a FakeBeer class that wraps a corresponding fake in [java-faker](https://github.com/DiUS/java-faker), to provide all the fake beer your code can drink.

## Technical Details
* Added `fakeBeer` to `FakeContext`.
* Added a `FakeBeer` class to contain values obtained from `java-faker`.
* Added a `FakerBeer` alias to `FakerTypeAliases`.
* Added a test to `FakerContextTest` for `fakeBeer`.
* Added a `FakeBeerTest` test class to test `FakeBeer`.

## Code Samples
```kotlin
fun main() {
    // fakeBeer: FakeBeer(name=Koors, style=Lager, hop=Cashmere, malt=Caramel, yeast=Pilsen)
    fakek { println("fakeBeer: $fakeBeer") }
}
```

Reviewers: @CodyEngel

### CODE REVIEW

**Comment by CodyEngel** [comment]
Hey @mattkimmel the changes are looking good although there are merge conflicts. Can you resolve those and tag me once they are resolved? From there I can review and merge these changes, thank you!

**Comment by mattkimmel** [comment]
Hi @CodyEngel -- I just resolved the merge conflicts. Let me know if there's anything else I can do for this PR!

**Review by CodyEngel — APPROVED** [review]
Hey @mattkimmel these changes LGTM. These changes will likely be released next Monday as part of our `0.5` pre-release. Thank you for your contribution!

**Comment by CodyEngel** [comment]
Actually @mattkimmel -- it looks like Circle CI is a little confused. Can you close and re-open this PR? That should kick of a fresh build. I'd also recommend running `./gradlew detekt` prior to doing this, it looks like some files don't have a new line at the end of file which will fail on the `run_detekt` step.

**Pull request closed without merging**
