### PR TITLE
#45 FakeSSN

### LINKED ISSUE #45: Add Fake SSN
Add a `FakeSSN` instance to `FakeContext`. Please ensure that new properties are added in alphabetical order and well documented.

Here are points of reference from the `Faker` library:

```kotlin
val ssn = faker.idNumber()
ssn.valid()
ssn.invalid()
```

If you want to work on this please leave a comment so you can be assigned to this issue. Feel free to ask questions or open a draft PR if you are unsure on implementation details.

### PR DESCRIPTION
**Pull request by Nowele**
Closes #45 

## Description
Creation of FakeSSN as a wrapper for IdNumber that returns a valid SSN.

## Technical Details
1. Added FakeSSN data class to provide a fakeSSN with a constructor that accepts FakerSSN.
2. Added FakeSSNTest class to test the FakeSSN class.
3. Updated FakeContext to add fakeSSN and fakerSSN.
4. Updated FakeContextTest to test fakeSSN.
5. Updated FakerTypeAliases to add FakerSSN as an alias of IdNumber

## Code Samples
Please provide code samples for how these changes will be used by applications consuming this library. Here's an example:

```kotlin
fun main() {
    val fakeSSN: FakeSSN(ssn="AAA-GG-SSSS")
    fakek { println("fakeSSN: $fakeSSN") }
}
```

Reviewers: @CodyEngel

### CODE REVIEW

**Comment by Nowele** [comment]
Converted to draft since I haven't been assigned the issue yet, feel free to close if it was assigned to someone else :)

**Comment by CodyEngel** [comment]
Hey @Nowele assigned this to you, the initial changes look good. I was hoping to include `valid` and `invalid` options for SSN, it looks like you have `valid` could you add `invalid` as well? After that the changes should be good to merge. Thank you :)

**Comment by Nowele** [comment]
> Hey @Nowele assigned this to you, the initial changes look good. I was hoping to include `valid` and `invalid` options for SSN, it looks like you have `valid` could you add `invalid` as well? After that the changes should be good to merge. Thank you :)

Apologies for the delay! I've resolved conflicts and addressed your feedback.

**Review by CodyEngel — APPROVED** [review]
LGTM thanks @Nowele!

**Pull request merged**
