### PR TITLE
Add fake beer

### LINKED ISSUE #36: Add Fake Beer
Add a `FakeBeer` instance to `FakeContext`. Please ensure that new properties are added in alphabetical order and well documented.

Here are points of reference from the `Faker` library:

```kotlin
val beer = faker.beer()
beer.hop()
beer.malt()
beer.name()
beer.style()
beer.yeast()
```

If you want to work on this please leave a comment so you can be assigned to this issue. Feel free to ask questions or open a draft PR if you are unsure on implementation details.

### PR DESCRIPTION
**Pull request by mattkimmel**
Closes #36 

## Description
Creates a FakeBeer class that wraps a corresponding fake in [java-faker](https://github.com/DiUS/java-faker), to provide all the fake beer your code can drink.

## Technical Details
* Added `fakeBeer` to `FakeContext`.
* Added a `FakeBeer` class to contain values obtained from `java-faker`.
* Added a `FakerBeer` alias to `FakerTypeAliases`.
* Added a test to `FakerContextTest` for `fakeBeer`.
* Added a `FakeBeerTest` test class to test `FakeBeer`.

## Code Samples
```kotlin
fun main() {
    // fakeBeer: FakeBeer(name=Koors, style=Lager, hop=Cashmere, malt=Caramel, yeast=Pilsen)
    fakek { println("fakeBeer: $fakeBeer") }
}
```

Reviewers: @CodyEngel

### CODE REVIEW

**Comment by mattkimmel** [comment]
Hi @CodyEngel, here's the new PR as per your request. I'm having trouble getting the `detekt` libs (can't connect to that repository at the moment), but I did fix the newline issue.

**Comment by CodyEngel** [comment]
Awesome thank you @mattkimmel, it looks like CircleCI still isn't able to run the checks. I'll look into this more this evening to see if I can get it resolved.

**Review by CodyEngel — APPROVED** [review]
Changes look good to me @mattkimmel, not sure why Circle wasn't building against your fork but once I resolved new merge conflicts it started working 🤷‍♂️

**Comment by mattkimmel** [comment]
No worries, Circle can be weird. Happy Hacktoberfest!

**Pull request merged**
